//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiCuitBeta.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigiCuitBeta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /* 
        /// * Copyright (C) 2015 Theos
        /// *
        /// * This program is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// *
        /// * This program is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        /// * GNU General Public Li [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Circuit {
            get {
                return ResourceManager.GetString("Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /* 
        /// * Copyright (C) 2015 Theos
        /// *
        /// * This program is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// *
        /// * This program is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        /// * GNU General Public Li [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComponentPrototype {
            get {
                return ResourceManager.GetString("ComponentPrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /* 
        /// * Copyright (C) 2015 Theos
        /// *
        /// * This program is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// *
        /// * This program is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        /// * GNU General Public Li [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad no es un array..
        /// </summary>
        internal static string PropertyIsNotArray {
            get {
                return ResourceManager.GetString("PropertyIsNotArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad no es un booleano..
        /// </summary>
        internal static string PropertyIsNotBoolean {
            get {
                return ResourceManager.GetString("PropertyIsNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad no es un objeto RGB ni una cadena hexadecimal.
        /// </summary>
        internal static string PropertyIsNotColorObject {
            get {
                return ResourceManager.GetString("PropertyIsNotColorObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad no es un numero..
        /// </summary>
        internal static string PropertyIsNotNumber {
            get {
                return ResourceManager.GetString("PropertyIsNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad no es un objeto..
        /// </summary>
        internal static string PropertyIsNotObject {
            get {
                return ResourceManager.GetString("PropertyIsNotObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad no es una cadena..
        /// </summary>
        internal static string PropertyIsNotString {
            get {
                return ResourceManager.GetString("PropertyIsNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad es nula o no está definida..
        /// </summary>
        internal static string PropertyIsNullOrUndefined {
            get {
                return ResourceManager.GetString("PropertyIsNullOrUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cable tiene el mismo punto de origen y de destino..
        /// </summary>
        internal static string WireHasNoLength {
            get {
                return ResourceManager.GetString("WireHasNoLength", resourceCulture);
            }
        }
    }
}
